[package]
name = "Tagless_Final"
version = "0.1.0"
authors = ["Frédéric Cabestre <frederic.cabestre@sigusr.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
